version: '3.8'

services:
  school-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school-frontend
    restart: always
    ports:
      - "3000:3000"
      - "80:3000"
